export interface GameData {
  status: string,
  gameState?: string,
  gameToken?: string,
  playerToken?: string,
  host?: string,
  iteration?: number,
  started?: boolean,
  finished?: boolean,
  winningRole?: string,
  playerTokens?: string[],
  playerNames?: string[],
  playerRoles?: string[],
  substate?: string,
  ownWord?: string,
  ownGuesses?: string[],
  ownIncorrectGuesses?: number,
  opponentGuesses?: string[],
  opponentIncorrectGuesses?: number,
  opponentWord?: string[]
}
